config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'home/updateStatus/:task/:statusVal', to: 'home#updateStatus'
  get 'home/postComment'
  
  resources :projects do
    resources :tasks
  end
  namespace :project do
    resources :tasks
  end
  devise_for :users 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def status
      return 'not-started' if tasks.none?

      if tasks.all? { |task| task.complete? }
        'complete'
      elsif tasks.any? { |task| task.in_progress? || task.complete? }
        'in-progress'
      else
        'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) *100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def login
    if request.post?
      if params[:username]=="kush" && params[:password]=="123456"
        session[:admin]="kush"
        redirect_to projects_path
      else
        flash[:notice]="Invalid username/password"
        render :action => "login"
      end
    end
  end

  def logout
    session[:admin]=nil
    flash[:notice]="You are logged out"
    redirect_to :action => :login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_for (resources)
        home_index_url
    end
    def after_sign_out_for (resources)
        home_index_url
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.all
    @tasks = Task.all
    @users = User.all
  end
  def updateStatus
    @taskToUpdate = Task.find(params[:task])
    @status = params[:statusVal]
    @taskToUpdate.update_attribute(:status, @status)
    redirect_to(home_index_url)
  end
  def postComment
    comment_hash = {}
    comment_hash[:user_id] = params[:user_id]
    comment_hash[:task_id] = params[:task_id]
    comment_hash[:commentText] = params[:commentText]
    @comment = Comment.new(comment_hash)
    if @comment.save
      flash[:notice]="Comment posted successfully..."
      redirect_to(home_index_url)
    else
      flash[:notice]="Error posting comment..."
      redirect_to(home_index_url)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
    @users = User.all
    @comments = Comment.all
    @tasks = Task.all
  end

  # GET /projects/new
  def new
    @project = Project.new
    @users = User.all
  end

  # GET /projects/1/edit
  def edit
    @users = User.all
  end

  # POST /projects or /projects.json
  def create
    @users = User.all
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :employee, :startdate, :enddate)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
    @users = User.all
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy
    Comment.where(task_id: @task.id).destroy_all
    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.all.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :empl, :start, :end, :status, :project_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/login.html.erb
<div class="container-admin">
	<div class="screen">
		<div class="screen__content">
        <%= form_with url:"/admin/login", :html => {:class => 'login'}, method: :post do |form| %>
            <h1>Manager Login</h1>
				<div class="login__field">
					<i class="login__icon fas fa-user"></i>
                    <%= form.text_field :username, placeholder: 'Username', class: 'login__input pl-4' %>
				</div>
				<div class="login__field">
					<i class="login__icon fas fa-lock"></i>
                    <%= form.password_field :password, placeholder: 'Password', class: 'login__input pl-4' %>
				</div>
				<button class="button login__submit">
					<span class="button__text">Log In Now</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>				
                <% end %>
			<div class="social-login">
				<h3>log in via</h3>
				<div class="social-icons">
					<a href="https://www.instagram.com/accounts/login/" class="social-login__icon fab fa-instagram"></a>
					<a href="https://www.facebook.com/" class="social-login__icon fab fa-facebook"></a>
					<a href="https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoiZW4ifQ%3D%3D%22%7D" class="social-login__icon fab fa-twitter"></a>
				</div>
			</div>
		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>		
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>		
	</div>
</div>
<script>
	document.body.style.background = 'linear-gradient(90deg, #C7C5F4, #776BCC)'
</script>

app/views/home/updateStatus.html.erb
<%= @taskToUpdate.name %>
<%= @status %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='nav-hidden-menu' id='nav-hidden'>
      <a href='/home/index'>My Dashboard</a>
      <%= link_to 'Edit profile', edit_user_registration_path %> 
      <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
    </div>
  
    <% msg='' %>
  <% case Time.now.strftime("%H").to_i %>
  <% when 1..11 then msg="Morning" %>
  <% when 12..16 then msg="Afternoon" %>
  <% when 16..24 then msg="Evening" %>
  <% else msg="Night" %>
  <% end %>
  
  <div class='w-100 bg-dark d-flex text-white pr-3 justify-content-between align-items-center' id='nav-top'>
    <% if user_signed_in? %>
    <div>
  <img src="/assets/logo1.jpeg" height='50px' width='50px' class='' >
    <a class='nav-link-item p-3' href='/home/index'>Home</a>
    </div>
    <span>Good <%= msg+' '+current_user.name %></span>
    <div class='d-flex align-items-center'>
      <div class='div-user-search'>
        <input type='text' name='user-search' class='user-search' placeholder='Search'>
        <i class="fas fa-search mr-1 user-icon-login" onclick='openSearchBox()'></i>
        <i class="fas fa-close mr-1 user-icon-login" id='user-search-empty' onclick='closeSearchBox()' style='display:none'></i>
      </div>
      <i class="fas fa-user mr-1 user-icon-login" onclick='hideMenu()'></i>
    </div>
  <% else %>
  
  <% if session[:admin].nil? %>
  <div>
  <img src="/assets/logo1.jpeg" height='50px' width='50px' class='' >
  <a class='nav-link-item p-3' href='/users/sign_in'>Home</a>
  </div>
  <span>Project Management</span>
  <div>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link text-white bg-info p-2 rounded mr-2'  %> 
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link text-white bg-info p-2 rounded'  %>
    </div>
  <% else %>
  <div>
  <img src="/assets/logo1.jpeg" height='50px' width='50px' class='' >
  <a class='nav-link-item p-3' href='/projects'>Home</a>
  </div>
  <span>Project Management</span>
  <div class='d-flex align-items-center'>
    <div class='div-user-search'>
          <input type='text' name='user-search' class='user-search' placeholder='Search'>
          <i class="fas fa-search mr-1 user-icon-login" onclick='openSearchBox()'></i>
          <i class="fas fa-close mr-1 user-icon-login" id='user-search-empty' onclick='closeSearchBox()' style='display:none'></i>
        </div>
    <%= link_to "Logout", admin_logout_path, :class => 'navbar-link text-white bg-info p-2 rounded'  %>
  </div>
  <% end %>
  <% end %>
    </div>

    <div class="alert-box">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    

  
      
    </div>
    
    <%= yield %>



    <script>
      function hideMenu(){
        if(document.getElementById('nav-hidden').style.display=='none'||document.getElementById('nav-hidden').style.display==''){
          document.getElementById('nav-hidden').style.display='block'
        }
        else{
          document.getElementById('nav-hidden').style.display='none'
        }
      }
      function openSearchBox(){
        if(document.getElementsByClassName('user-search')[0].style.display==''||document.getElementsByClassName('user-search')[0].style.display=='none'){
          document.getElementsByClassName('div-user-search')[0].style.border = '1px solid rgb(253, 253, 253, 0.1)';
          document.getElementsByClassName('user-search')[0].style.display = 'inline-block'
          document.getElementById('user-search-empty').style.display='inline-block'
          document.getElementsByClassName('user-search')[0].focus()
        }
        else{
          var searchValue = document.getElementsByClassName('user-search')[0].value.toLowerCase()
          if(searchValue.trim()=='')return;
          var searchContent = document.getElementsByClassName('search-content')
          var flag = true;
          var id = '';
          for(var i=0;i<searchContent.length;i++){
            searchContent[i].style.backgroundColor='inherit';
            if(searchContent[i].innerText.toLowerCase().includes(searchValue)){
              searchContent[i].style.backgroundColor='yellow';
              if(flag){
                id = searchContent[i].id;
                flag = false;
              }
            }
          }
          if(!flag){
            window.location.href = `#${id}`;
            window.scrollBy(0,-50)
          }

        }
      }

      function closeSearchBox(){
        document.getElementsByClassName('div-user-search')[0].style.border = 'none';
          document.getElementsByClassName('user-search')[0].style.display = 'none'
          document.getElementById('user-search-empty').style.display='none'
      }
      
    </script>
       
  </body>
</html>

app/views/projects/edit.html.erb
<div class='container'>
<%= link_to 'Back', @project, class: 'btn btn-secondary my-3' %>
<div class="card">
    <div class="card-body">
        <h2 class='card-title mb-4'>
            <span>Editing Project</span>
        </h2>

        <%= render 'form', project: @project %>
    </div>
</div>
</div>
<script>
    document.body.style.backgroundColor='none'
    document.body.style.backgroundImage="url('/assets/bg2.jpg')"
    document.body.style.backgroundSize= '100% 100%';
    document.body.style.backgroundRepeat= 'no-repeat';
    document.body.style.backgroundAttachment= 'fixed';
</script>

app/views/projects/index.html.erb
<% if session[:admin].nil? %>
<% if user_signed_in? %>
<script type="text/javascript">
    window.location.href="/home/index"
  </script>
  <% else %>
  <script type="text/javascript">
    window.location.href="/users/sign_in"
  </script>
  <% end %>
<% end %>

<div class='container mt-5'>
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span>Projects</span>
      <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
    </h2>

    <% @projects.each do |project| %>
      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card card-zoom project-card mb-3">
          <div class="card-body">
            <div class="mb-3">
              <span class="badge badge-<%= project.badge_color %>">
                <%= project.status %>
              </span>
              <span class='text-secondary'>
                <small>
                  <%= project.percent_complete %>% complete
                  (<%= project.total_complete %>/<%= project.total_tasks %> tasks)
                </small>
              </span>
            </div>
            <h5 class='card-title text-dark search-content' id='project-search-<%= project.id %>' style='width:max-content'><b><%= project.name %></b></h5>
            <p class='text-secondary'><%= project.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>
<script>
    document.body.style.backgroundColor='none'
    document.body.style.backgroundImage="url('/assets/bg4.jpg')"
    document.body.style.backgroundSize= '100% 100%';
    document.body.style.backgroundRepeat= 'no-repeat';
    document.body.style.backgroundAttachment= 'fixed';
    
        
</script>

app/views/projects/new.html.erb
<div class='container'>
<%= link_to 'Back', projects_path, class: 'btn btn-secondary my-3' %>
<div class="card">
    <div class="card-body">
        <h2 class='card-title mb-4'>
            <span>New Project</span>
        </h2>

        <%= render 'form', project: @project %>
    </div>
</div>
</div>
<script>
document.body.style.backgroundColor='none'
    document.body.style.backgroundImage="url('/assets/bg2.jpg')"
    document.body.style.backgroundSize= '100% 100%';
    document.body.style.backgroundRepeat= 'no-repeat';
    document.body.style.backgroundAttachment= 'fixed';

</script>

app/views/projects/show.html.erb
<div class='container user-proj'>
<div class='sidebar-hidden'>
    <div class='side-title'>
        <div id='team-type'></div>
        <i onclick='closeSideBar()' class='fas fa-times'></i>
    </div>
    <div class='side-body'>
        <i class="fas fa-users side-i-i"></i>
        <div id='taskNameSide'>Task : </div>
    </div>
    <div class='sidebar-hidden1'></div>
</div>
<div class='sidebar-hidden-comment'>
</div>

<div style='display:none'>
    <% @users.each do |user| %>
            <div id='user-hidden-<%= user.id %>'><%= user.name %></div>
    <% end %>
</div>

<div class="container">
<% thisProjEmps = @project.employee %>
<% @tasks.where(project_id: @project.id).each do |taskThisProj| %>
  <% thisProjEmps+=taskThisProj.empl %>
<% end %>

<%= link_to 'Back', projects_path, class: 'btn btn-secondary my-3' %>
<div class="bg-white rounded p-4">
  <div class="">
    <div class='d-flex justify-content-between'>
      <h2><%= @project.name %></h2>
      <div>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', @project, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
    <div class='d-flex justify-content-end'>
    <button class="btn-read-cmnt1" onclick="openSideBar('<%= thisProjEmps %>','<%= @project.name %>','Project')">Project Team</button>
    </div>

    <div class="m-4 mb-5 p-4 rounded task-form">
      <h6>Add task</h6>

        <%= form_with(model: [@task.project, @task], html: { class: 'form-inline' }) do |f| %>
          <% if @task.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
        
              <ul>
              <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        
          <%= f.hidden_field :status, value: 'not-started' %>
          <div class="form-group w-100 mb-4">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Enter task name...' %>
          </div>

          <div class="form-group w-100 mb-4">
            <%= f.text_area :description, class: 'form-control', placeholder: 'Enter Description...' %>
          </div>


          <%= f.hidden_field :empl, id:'empl-new-task' %>

          <div class='custom-checkbox width-checkbox'>
            <p>Employee</p>
            <div class='select'>
                  <div class='placeholder' onclick='showcheckbox()'><span>Select Employee</span><span id='custom-i'><i class="fas fa-caret-down"></i></span></div>
                  <% @users.each do |user| %>
                    <div class='custom-option'><input type='checkbox' id=<%= user.id %> onchange='checkbox(this.id)'><span><%= user.name %></span></div>
                  <% end %>
            </div>
          </div>

          <div class="form-group w-100 my-2">
            <%= f.label :start %><br />
            <%= f.datetime_select :start, {}, class: 'form-control mx-1' %>
          </div>
          <div class="form-group w-100 my-2">
            <%= f.label :end %><br />
            <%= f.datetime_select :end, {}, class: 'form-control mx-1' %>
          </div>
          <div class="form-group w-100 mt-2">
            <%= f.submit class: 'btn btn-primary px-5' %>
          </div>
        <% end %>
    </div>
      <h4 class='pt-3'>Tasks</h4>
      <% @project.tasks.each do |task| %>
        <% if task.persisted? %>
          <div class="card mb-3 card-zoom">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <span class="badge badge-<%= task.badge_color %> mb-3"><%= task.status %></span>
                <div>
                      <%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-light btn-sm' %>
                      <%= link_to 'Delete', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-dark btn-sm' %>
                    
                </div>
              </div>
              <h5 class='card-title mb-2 d-flex justify-content-between'>
                <span class='search-content' id='task-search-<%= task.id %>'><%= task.name %></span>
                <button class="btn-read-cmnt1" onclick="openSideBar('<%= task.empl %>','<%= task.name %>','Task')">Task Team</button>
              </h5>
              <p><%= task.description %></p>
              <hr id='comment-hr-<%= task.id %>'>
              <h6 class='text-primary' id='comment-capt-<%= task.id %>'>Comments</h6>
              <div class='comment-card p-3 rounded' id='comment-card-<%= task.id %>'>
              <% @comments.each do |comment| %>
                <% if comment.task_id == task.id %>
                    <div class='comment-each'>
                      <div class='d-flex align-items-center'>
                        <span class='userNameComment'><%= User.find(comment.user_id).name %></span>
                        <span class='dateComment'><%= comment.created_at.strftime('%-d %b %Y %I:%M %p') %></span>
                      </div>
                      <span class='commentx'><%= comment.commentText %></span>
                    </div>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>

        <% end %>
      <% end %>
    
  </div>
</div>

</div>


<script>
 function showcheckbox(){
  if(document.getElementsByClassName('select')[0].style.height==''||document.getElementsByClassName('select')[0].style.height=='35px'){
    document.getElementsByClassName('select')[0].style.height='min-content';
    document.getElementById('custom-i').innerHTML='<i class="fas fa-caret-up"></i>'
  }
  else {
    document.getElementsByClassName('select')[0].style.height='35px'
    document.getElementById('custom-i').innerHTML='<i class="fas fa-caret-down"></i>'
  }
 }

 function checkbox(id){
  if(document.getElementById(id).checked){
    document.getElementById('empl-new-task').value+=(id+'--')
  }
  else{
    if(document.getElementById('empl-new-task').value.includes(id)){
      document.getElementById('empl-new-task').value = document.getElementById('empl-new-task').value.replace((id+'--'),'')
    }
  }
 }
 for(var i=0;i<document.getElementsByClassName('comment-card').length;i++){
  if(document.getElementsByClassName('comment-card')[i].innerHTML.trim()==''){
    document.getElementsByClassName('comment-card')[i].style.display = 'none'
    document.getElementById('comment-capt-'+document.getElementsByClassName('comment-card')[i].id.split('-')[2]).style.display='none'
    document.getElementById('comment-hr-'+document.getElementsByClassName('comment-card')[i].id.split('-')[2]).style.display='none'
  }
}
function openSideBar(users,taskName,type){
        document.getElementsByClassName('sidebar-hidden1')[0].innerHTML="";
        document.getElementById('taskNameSide').innerText=`${type} : ${taskName}`;
        userArr = users.split('--')
        userArr = userArr.filter((item, index) => userArr.indexOf(item) === index);
        for(var i=0;i<userArr.length;i++){
            if(userArr[i].length>0){
                var userEach = document.createElement('p');
                userEach.innerText = document.getElementById('user-hidden-'+userArr[i]).innerHTML;
                console.log(userEach);
                document.getElementsByClassName('sidebar-hidden1')[0].appendChild(userEach);
            }
        }
        document.getElementById('team-type').innerText = `${type} Team`
        document.getElementsByClassName('sidebar-hidden')[0].style.width = '300px'
    }
    function closeSideBar(){
        document.getElementsByClassName('sidebar-hidden')[0].style.width = '0'
    }
    document.body.style.backgroundColor='none'
    document.body.style.backgroundImage="url('/assets/bg4.jpg')"
    document.body.style.backgroundSize= '100% 100%';
    document.body.style.backgroundRepeat= 'no-repeat';
    document.body.style.backgroundAttachment= 'fixed';

</script>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Empl</th>
    <th>Start</th>
    <th>End</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.empl %></td>
    <td><%= task.start %></td>
    <td><%= task.end %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Empl:</b>
  <%= @task.empl %>
</p>

<p>
  <b>Start:</b>
  <%= @task.start %>
</p>

<p>
  <b>End:</b>
  <%= @task.end %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>